### ISSUE TITLE
Would you consider dual licensing?

### ISSUE THREAD

**Issue by projectgus** [crossbowerbt/dhcpserver#1]
Hi,

I'm looking for a simple dhcp server that I can adapt into a new BSD licensed embedded system framework (esp-open-rtos). Yours is my preferred candidate, it looks perfect and it shouldn't be too hard to port to a microcontroller IP stack!

However I want to keep esp-open-rtos as BSD licensed. It's unclear to me whether how the "coffee license" works regarding relicensing!

Would you possibly consider dual-licensing your dhcpserver as either coffee license or New BSD, with a non-binding request that BSD licensees please buy you a cofee? That way I can include your project!

I will also gladly buy you a coffee, and if the porting efforts come up with any upstream-friendly changes then I will submit those back as PRs. :)

Of course it's your project so if you want to keep the license the way it is, that's absolutely fine. I just thought I'd ask on the offchance.

Cheers,

Angus

**Comment by projectgus** [comment]
Someone pointed out that "use the code as you wish" might include relicensing it. So if I can offer you a coffee and then relicense the code under a standard BSD License, and comply with the "coffee license" that way, then that would be great. Let me know if that suits you. :)

(If I was to do that, I'd of course leave your copyright statement & attribution in place, and make a non-binding request in there for other people to offer you a coffee.)

**Comment by crossbowerbt** [comment]
Hi,

I'm happy you found the cade useful.

The coffee licence is indeed a no-licence: you can do what you want with
the code, you may even re-license it under BSD.

So you can of course use the code in an embedded system :)

I have written the server as an university project in networking,
and I tried to keep it very short and simple.

However I tested it only under normal usage: if you plan to use it for a
commercial project I suggest to do some testing to see if it work
correctly under your system :)

Best Regards,
Emanuele

PS: if you find bugs or write some modifies that may be useful, I would
be happy to include it in the code ;)

**Comment by projectgus** [comment]
OK, sounds great. I will do all that, thanks.

Fully prepared to do testing and modifications. I just didn't want to start from scratch if I could help it, there are already dozens of single-contributor dhcp server projects on github so I figured better to work on something that already exists.

BTW, would you like a coffee? I don't know what part of the world you're in but I can PayPal/bitcoin/something you some money, or you can collect in person from Melbourne, Australia some time in the future. :)

**Comment by crossbowerbt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,

No problem for the coffee :)
Italy is a bit too far from Australia, but who knows what the future
may bring...

After our exchange of emails I read some articles from your site, and
found them really well written.

In particular
http://projectgus.com/2013/05/encrypted-rootfs-over-ssh-with-debian-whee
zy/
is very interesting, and I didn't know tools that allow an encrypted
boot via ssh already existed.

But I'm still a bit reticent to use that method, since if, let's say,
someone access the server-room after the boot and doesn't shutdown the
server, the filesystem remains accessible.

I don't know if a better tradeoff is possible in reality...

I am also working on embedded system and this is why I usually write
stand-alone software.

In fact the dhcp-server was in pair with the tftp-server, for booting
a memoryless cisco device: the dhcp cat provide an option to specify
the location of the IOS image, obtained by the device via tftp...

Ok, let's stop the blabbering here :)

Good luck for your projects!
Emanuele

On 06/04/2015 11:13 PM, Angus Gratton wrote:

> OK, sounds great. I will do all that, thanks.
> 
> Fully prepared to do testing and modifications. I just didn't want
> to start from scratch if I could help it, there are already dozens
> of single-contributor dhcp server projects on github so I figured
> better to work on something that already exists.
> 
> BTW, would you like a coffee? I don't know what part of the world
> you're in but I can PayPal/bitcoin/something you some money, or you
> can collect in person from Melbourne, Australia some time in the
> future. :)
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/crossbowerbt/dhcpserver/issues/1#issuecomment-1090
> 53903>.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2.0.20 (GNU/Linux)

iEYEARECAAYFAlVwxDwACgkQYSLd5SKwKoSwVACdHHAzScDg1TeCsROyLSkFqESV
t5MAn1KkboFtgobkYQfHQz+chQJWBsqD
=3pUr
-----END PGP SIGNATURE-----

**Comment by projectgus** [comment]
Hi,

Interesting stuff, thanks. I'll let you know how I get on with the DHCP server. I don't have complex requirements either. It might be a little while before I actually get around to working with it, I was just looking around trying to plan how all these pieces might come together.

Re: headless disk encryption, there are definitely various physical attacks you could use to get disk keys from a running system. It all depends on what your threat model is, I guess.

Cheers,

Angus

**Comment by amakukha** [comment]
Great code quality. Thanks, Emanuele! 
When you are ever in Shenzhen or Hong Kong, let me know. I'll show you where the best coffee is in this area :)

**Comment by crossbowerbt** [comment]
Thanks! :D

2016-11-22 16:53 GMT+01:00 Andriy Makukha notifications@github.com:
